OpCodes = {};

OpCodes.LOGIN_RESULT = -1;
OpCodes.PING_RESULT = -3;
OpCodes.UDP_CONNECT_MESSAGE = -5; 
OpCodes.PLAYER_READY_MESSAGE = -7; 
OpCodes.PLAYER_CONNECT_MESSAGE = -101; 
OpCodes.PLAYER_DISCONNECT_MESSAGE = -103;
